name: 06-github-repository-variables

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Printing predfined variables
        run: |
          echo "$GITHUB_WORKFLOW"
          echo "$GITHUB_ACTION"
          echo "$GITHUB_REPOSITORY"
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.0
      - name: Maven Build
        run: |
          mvn clean package
          pwd && ls -l
          ls -l ${{ vars.MVN_TARGET_FOLDER }}
          du -sh ${{ vars.MVN_TARGET_FOLDER }}
          du -sh ${{ vars.MVN_TARGET_FOLDER }}/${{ vars.MVN_WAR_FILE_NAME }}
      - name: Copying war file to tmp folder
        run: |
          cp ${{ vars.MVN_TARGET_FOLDER }}/${{ vars.MVN_WAR_FILE_NAME }} ${{ vars.COPY_TARGET_FOLDER }}
          ls -l ${{ vars.COPY_TARGET_FOLDER }}